# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "3600:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    dns:
      - 8.8.8.8
    volumes:
      - /var/lib/mysql/auto.cnf:/etc/mysql/conf.d/config-file.cnf
      - /var/lib/mysql/:/var/lib/mysql:rw
  bookstore:
    image: bookstore
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
     - db
    dns:
      - 8.8.8.8
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5026:5026
