# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  bookstore:
    image: bookstore
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5026:5026
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
